# Generated by Django 6.1 on 2026-09-11 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_organization_alter_experience_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('leadership', 'Leadership & Management'), ('event', 'Event & Project Coordination'), ('communication', 'Communication & Stakeholder Relations'), ('technical', 'Technical')], default='technical', max_length=20)),
                ('proficiency', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=1)),
                ('impact', models.CharField(blank=True, max_length=255)),
                ('context', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
