# Generated by Django 6.1 on 2026-09-27 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='endorsed_by',
            field=models.ManyToManyField(blank=True, related_name='endorsed_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
